# Datasource
spring:
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # H2
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto=create-drop:
      show_sql: true